### ISSUE TITLE
width 方法是否可以保持与 jQuery API一致

### ISSUE THREAD

**Issue by alvinhui** [kissyteam/node#1]
不知道这是一个 bug 还是有意为之，`Node('.class').width(100)` 只会改变第一个匹配节点的宽度，而不是全部。

看示例：

jQuery 2.1.1：http://jsbin.com/vogupurimo/4/
KISSY 6：http://jsbin.com/manoponeto/1/

**Comment by mariodu** [comment]
现在在用kissy 5，貌似好多方法都是这样子的。NodeList中只处理第一个元素。
